package br.edu.uepb.cg;

import br.edu.uepb.cg.dialog.DialogSobre;
import static br.edu.uepb.cg.dialog.DialogDesenhaObjetos.listaGLOBAL;
import br.edu.uepb.cg.dialog.DialogCharts;
import br.edu.uepb.cg.dialog.DialogDesenhaObjetos;
import br.edu.uepb.cg.enums.RasterizacaoEnum;
import br.edu.uepb.cg.panels.PanelGatoArnold;
import br.edu.uepb.cg.panels.PanelFiltros;
import br.edu.uepb.cg.panels.PanelHistorgrama;
import br.edu.uepb.cg.panels.PanelMenu2D;
import br.edu.uepb.cg.panels.PanelMenuCircunferencia;
import br.edu.uepb.cg.panels.PanelMenuFiltros;
import br.edu.uepb.cg.panels.PanelMenuOperacoes;
import br.edu.uepb.cg.panels.PanelMenuRasterizacao;
import br.edu.uepb.cg.panels.PanelMenuSistemaSolar;
import br.edu.uepb.cg.panels.PanelMenuTransformacoes;
import br.edu.uepb.cg.panels.PanelOperacoes;
import br.edu.uepb.cg.panels.PanelPlanoCartesiano;
import br.edu.uepb.cg.panels.PanelTranformacoes;
import br.edu.uepb.cg.retas.Circunferencia;
import br.edu.uepb.cg.retas.Ponto;
import br.edu.uepb.cg.retas.Rasterizacao;
import br.edu.uepb.cg.sistemacoordenadas.FuncoesDeNormalizacao;
import br.edu.uepb.cg.transformacao2D.SistemaSolar;
import br.edu.uepb.cg.transformacao2D.Transformacoes2D;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.util.List;
import javax.swing.JPanel;

/**
 * Classe que representa a tela inicial da aplicação
 *
 * @author Douglas Rafael
 */
public class App extends javax.swing.JFrame {

    private final PanelMenuRasterizacao panelMenuRasterizacao;
    private final PanelMenuCircunferencia panelMenuCircunferencia;
    private final PanelMenuFiltros panelMenuFiltros;
    private final PanelMenuOperacoes panelMenuOperacoes;
    private final PanelMenuTransformacoes panelMenuTransformacoes;
    private final PanelMenu2D panelMenu2D;
    private final PanelMenuSistemaSolar panelMenuSistemaSolar;

    private final PanelFiltros panelFiltros;
    private final PanelOperacoes panelOperacoes;
    private final PanelTranformacoes panelTransformacoes;
    private final PanelHistorgrama panelHistograma;
    private final PanelGatoArnold panelArnold;

    /**
     * Construtor
     */
    public App() {
        panelMenuRasterizacao = PanelMenuRasterizacao.getInstance();
        panelMenuCircunferencia = PanelMenuCircunferencia.getInstance();
        panelMenuFiltros = PanelMenuFiltros.getInstance();
        panelMenuOperacoes = PanelMenuOperacoes.getInstance();
        panelMenuTransformacoes = PanelMenuTransformacoes.getInstance();
        panelHistograma = PanelHistorgrama.getInstance();
        panelArnold = PanelGatoArnold.getInstance();
        panelMenu2D = PanelMenu2D.getInstance();
        panelMenuSistemaSolar = PanelMenuSistemaSolar.getInstance();

        panelFiltros = PanelFiltros.getInstance();
        panelOperacoes = PanelOperacoes.getInstance();
        panelTransformacoes = PanelTranformacoes.getInstance();

        initComponents();
        openMenuReta(null);
        sistemaCoordenadas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        panelMenuLeft = new javax.swing.JPanel();
        panelBox = new javax.swing.JPanel();
        panelFooter = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelDCX = new javax.swing.JLabel();
        labelDCY = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelNDCY = new javax.swing.JLabel();
        labelNDCX = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelX = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelY = new javax.swing.JLabel();
        panelPlanoCartesiano = br.edu.uepb.cg.panels.PanelPlanoCartesiano.getInstance();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemReta = new javax.swing.JMenuItem();
        menuItemCircuferencia = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItem2D = new javax.swing.JMenuItem();
        menuItem3D = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuSobre1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Computação Gráfica - UEPB");
        setExtendedState(6);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("assets/images/icon.png")));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setName("framePrincipal"); // NOI18N

        panelMenuLeft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelMenuLeft.setMinimumSize(new java.awt.Dimension(240, 0));
        panelMenuLeft.setPreferredSize(new java.awt.Dimension(240, 2));

        javax.swing.GroupLayout panelMenuLeftLayout = new javax.swing.GroupLayout(panelMenuLeft);
        panelMenuLeft.setLayout(panelMenuLeftLayout);
        panelMenuLeftLayout.setHorizontalGroup(
            panelMenuLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );
        panelMenuLeftLayout.setVerticalGroup(
            panelMenuLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );

        panelFooter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelFooter.setMinimumSize(new java.awt.Dimension(170, 100));
        panelFooter.setPreferredSize(new java.awt.Dimension(170, 327));

        jLabel3.setBackground(new java.awt.Color(209, 117, 117));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<html><h3 align=\"center\">Coordenadas<br/>de Entrada</h3></html>");
        jLabel3.setMinimumSize(new java.awt.Dimension(170, 54));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(170, 54));

        jLabel4.setBackground(new java.awt.Color(209, 117, 117));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("<html><h3 align=\"center\">Coordenadas<br/>de Saída</h3></html>");
        jLabel4.setMinimumSize(new java.awt.Dimension(170, 54));
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(170, 54));

        jLabel5.setBackground(new java.awt.Color(209, 117, 117));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html><h3 align=\"center\">Coordenadas<br/>de Normalização</h3></html>");
        jLabel5.setMinimumSize(new java.awt.Dimension(170, 54));
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(170, 54));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("DCX:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("DCY:");

        labelDCX.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelDCX.setText("0");

        labelDCY.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelDCY.setText("0");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("NDCY:");

        labelNDCY.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNDCY.setText("0");

        labelNDCX.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNDCX.setText("0");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("NDCX:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("X:");

        labelX.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelX.setText("0");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Y:");

        labelY.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelY.setText("0");

        javax.swing.GroupLayout panelFooterLayout = new javax.swing.GroupLayout(panelFooter);
        panelFooter.setLayout(panelFooterLayout);
        panelFooterLayout.setHorizontalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFooterLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelY)
                            .addComponent(labelX)))
                    .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFooterLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFooterLayout.createSequentialGroup()
                                    .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelDCY)
                                        .addComponent(labelDCX)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFooterLayout.createSequentialGroup()
                                    .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelNDCY)
                                        .addComponent(labelNDCX)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFooterLayout.setVerticalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelDCX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(labelDCY))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelNDCX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(labelNDCY))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labelX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(labelY))
                .addContainerGap(344, Short.MAX_VALUE))
        );

        panelPlanoCartesiano.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelPlanoCartesiano.setPreferredSize(new java.awt.Dimension(550, 550));

        javax.swing.GroupLayout panelPlanoCartesianoLayout = new javax.swing.GroupLayout(panelPlanoCartesiano);
        panelPlanoCartesiano.setLayout(panelPlanoCartesianoLayout);
        panelPlanoCartesianoLayout.setHorizontalGroup(
            panelPlanoCartesianoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );
        panelPlanoCartesianoLayout.setVerticalGroup(
            panelPlanoCartesianoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelBoxLayout = new javax.swing.GroupLayout(panelBox);
        panelBox.setLayout(panelBoxLayout);
        panelBoxLayout.setHorizontalGroup(
            panelBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoxLayout.createSequentialGroup()
                .addComponent(panelPlanoCartesiano, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBoxLayout.setVerticalGroup(
            panelBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPlanoCartesiano, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
            .addComponent(panelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );

        menuBar.setPreferredSize(new java.awt.Dimension(104, 40));

        jMenu1.setText("Desenhar");

        menuItemReta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        menuItemReta.setText("Reta");
        menuItemReta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuReta(evt);
            }
        });
        jMenu1.add(menuItemReta);

        menuItemCircuferencia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        menuItemCircuferencia.setText("Circuferência");
        menuItemCircuferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuCircunferencia(evt);
            }
        });
        jMenu1.add(menuItemCircuferencia);

        menuBar.add(jMenu1);

        jMenu3.setText("Transformações");

        menuItem2D.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.SHIFT_MASK));
        menuItem2D.setText("2D");
        menuItem2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openTrans2D(evt);
            }
        });
        jMenu3.add(menuItem2D);

        menuItem3D.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.SHIFT_MASK));
        menuItem3D.setText("3D");
        menuItem3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openTrans3D(evt);
            }
        });
        jMenu3.add(menuItem3D);

        menuBar.add(jMenu3);

        jMenu2.setText("Processamento de Imagens");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setText("Filtros");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuFiltros(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem5.setText("Operações");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuOperacoes(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem6.setText("Gato de Arnold ");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuArnold(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem7.setText("Transformação");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuTransformacoes(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem8.setText("Equalização/Histograma");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuEqualizacao(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        menuBar.add(jMenu2);

        menuSobre.setText("Outros");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem2.setText("Gráficos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openGraficos(evt);
            }
        });
        menuSobre.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem3.setText("Sistema Solar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openSistemaSolar(evt);
            }
        });
        menuSobre.add(jMenuItem3);

        menuBar.add(menuSobre);

        menuSobre1.setText("Sobre");
        menuSobre1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openAbout(evt);
            }
        });
        menuSobre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openAboutPressed(evt);
            }
        });
        menuBar.add(menuSobre1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMenuLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMenuLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1096, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuReta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuReta
        panelMenuLeft.setVisible(true);

        if (!panelFooter.isValid()) {
            setDefaultBox();
        }
        changeMenuLeft(panelMenuRasterizacao);
    }//GEN-LAST:event_openMenuReta

    private void openMenuCircunferencia(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuCircunferencia
        panelMenuLeft.setVisible(true);
        if (!panelFooter.isValid()) {
            setDefaultBox();
        }
        changeMenuLeft(panelMenuCircunferencia);
    }//GEN-LAST:event_openMenuCircunferencia

    private void openMenuFiltros(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuFiltros
        /**
         * Removendo os panels que não serão utilizados
         */
        panelFooter.setVisible(false);
        panelMenuLeft.setVisible(true);
        panelBox.removeAll();

        javax.swing.GroupLayout panelBoxLayout = new javax.swing.GroupLayout(panelBox);
        panelBox.setLayout(panelBoxLayout);
        panelBoxLayout.setHorizontalGroup(
                panelBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBoxLayout.createSequentialGroup()
                        .addComponent(panelFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
        );

        panelBoxLayout.setVerticalGroup(
                panelBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        changeMenuLeft(panelMenuFiltros);
    }//GEN-LAST:event_openMenuFiltros

    private void openMenuOperacoes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuOperacoes
        panelFooter.setVisible(false);
        panelMenuLeft.setVisible(true);
        panelBox.removeAll();

        javax.swing.GroupLayout panelBoxLayout = new javax.swing.GroupLayout(panelBox);
        panelBox.setLayout(panelBoxLayout);
        panelBoxLayout.setHorizontalGroup(
                panelBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBoxLayout.createSequentialGroup()
                        .addComponent(panelOperacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
        );

        panelBoxLayout.setVerticalGroup(
                panelBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelOperacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        changeMenuLeft(panelMenuOperacoes);
    }//GEN-LAST:event_openMenuOperacoes

    private void openMenuArnold(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuArnold
        panelFooter.setVisible(false);
        panelMenuLeft.setVisible(false);
        panelBox.removeAll();

        javax.swing.GroupLayout panelBoxLayout = new javax.swing.GroupLayout(panelBox);
        panelBox.setLayout(panelBoxLayout);
        panelBoxLayout.setHorizontalGroup(
                panelBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBoxLayout.createSequentialGroup()
                        .addComponent(panelArnold, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
        );

        panelBoxLayout.setVerticalGroup(
                panelBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelArnold, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }//GEN-LAST:event_openMenuArnold

    private void openMenuTransformacoes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuTransformacoes
        panelFooter.setVisible(false);
        panelMenuLeft.setVisible(true);
        panelBox.removeAll();

        javax.swing.GroupLayout panelBoxLayout = new javax.swing.GroupLayout(panelBox);
        panelBox.setLayout(panelBoxLayout);
        panelBoxLayout.setHorizontalGroup(
                panelBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBoxLayout.createSequentialGroup()
                        .addComponent(panelTransformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
        );

        panelBoxLayout.setVerticalGroup(
                panelBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelTransformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        changeMenuLeft(panelMenuTransformacoes);
    }//GEN-LAST:event_openMenuTransformacoes

    private void openMenuEqualizacao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuEqualizacao
        panelFooter.setVisible(false);
        panelMenuLeft.setVisible(false);
        panelBox.removeAll();

        javax.swing.GroupLayout panelBoxLayout = new javax.swing.GroupLayout(panelBox);
        panelBox.setLayout(panelBoxLayout);
        panelBoxLayout.setHorizontalGroup(
                panelBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBoxLayout.createSequentialGroup()
                        .addComponent(panelHistograma, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
        );

        panelBoxLayout.setVerticalGroup(
                panelBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelHistograma, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }//GEN-LAST:event_openMenuEqualizacao

    private void openTrans2D(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openTrans2D
//        new DialogDesenhaObjetos(this, true).setVisible(true);

        PanelPlanoCartesiano pPlanoCartersiano = PanelPlanoCartesiano.getInstance();
        pPlanoCartersiano.redesenha();

        panelMenuLeft.setVisible(true);
        if (!panelFooter.isValid()) {
            setDefaultBox();
        }
        changeMenuLeft(panelMenu2D);
    }//GEN-LAST:event_openTrans2D

    private void openTrans3D(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openTrans3D
//        new DialogDesenhaObjetos(this, true).setVisible(true);

        panelMenuLeft.setVisible(true);
        if (!panelFooter.isValid()) {
            setDefaultBox();
        }

        PanelPlanoCartesiano panelPlanoCartesiano3D = PanelPlanoCartesiano.getInstance();
        panelPlanoCartesiano3D.redesenha();
        panelPlanoCartesiano3D.desenhaEixoZ();

        changeMenuLeft(panelMenu2D);
    }//GEN-LAST:event_openTrans3D

    private void openGraficos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openGraficos
        new DialogCharts(this, true).setVisible(true);
    }//GEN-LAST:event_openGraficos

    private void openAbout(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openAbout
        new DialogSobre(this, true).setVisible(true);
    }//GEN-LAST:event_openAbout

    private void openAboutPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openAboutPressed
        new DialogSobre(this, true).setVisible(true);
    }//GEN-LAST:event_openAboutPressed

    private void openSistemaSolar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openSistemaSolar
        panelMenuLeft.setVisible(true);

        if (!panelFooter.isValid()) {
            setDefaultBox();
        }
        changeMenuLeft(panelMenuSistemaSolar);

        SistemaSolar sistemaSolar = new SistemaSolar();
        if (SistemaSolar.threadAnimation != null) {
            SistemaSolar.threadAnimation.stop();
        }
        sistemaSolar.startAnimation();
    }//GEN-LAST:event_openSistemaSolar

    /**
     * Coloca o box principal com o layout default
     */
    private void setDefaultBox() {
        if (!panelFooter.isVisible()) {
            panelBox.removeAll();

            javax.swing.GroupLayout panelBoxLayout = new javax.swing.GroupLayout(panelBox);
            panelBox.setLayout(panelBoxLayout);
            panelBoxLayout.setHorizontalGroup(
                    panelBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBoxLayout.createSequentialGroup()
                            .addComponent(panelPlanoCartesiano, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            panelBoxLayout.setVerticalGroup(
                    panelBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPlanoCartesiano, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                    .addComponent(panelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
            );

            panelFooter.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JLabel labelDCX;
    private javax.swing.JLabel labelDCY;
    private javax.swing.JLabel labelNDCX;
    private javax.swing.JLabel labelNDCY;
    private javax.swing.JLabel labelX;
    private javax.swing.JLabel labelY;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItem2D;
    private javax.swing.JMenuItem menuItem3D;
    private javax.swing.JMenuItem menuItemCircuferencia;
    private javax.swing.JMenuItem menuItemReta;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JMenu menuSobre1;
    private javax.swing.JPanel panelBox;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelMenuLeft;
    private static javax.swing.JPanel panelPlanoCartesiano;
    // End of variables declaration//GEN-END:variables

    /**
     * Altera o jPanel do menu esquerdo de acordo com o jPanel passado como
     * parâmetro
     *
     * @param panel O jPanel a ser populado
     */
    private void changeMenuLeft(JPanel panel) {
        panelMenuLeft.removeAll();
        panelMenuLeft.repaint();

        panelMenuLeft.setLayout(new GridLayout());
        panelMenuLeft.add(panel);

        panelMenuLeft.validate();
    }

    /**
     * Executa o algoritmo de rasterização da reta
     *
     * @param instance Instancia do PanelMenu que o chamou
     */
    public static void runResult(Object instance) {
        // Limpa o panelBody onde fica o plano cartesiano
        panelPlanoCartesiano.getGraphics().clearRect(0, 0, panelPlanoCartesiano.getWidth(), panelPlanoCartesiano.getHeight());
        panelPlanoCartesiano.paint(panelPlanoCartesiano.getGraphics()); // Desenha o plano cartesiano novamente

        if (instance instanceof PanelMenuRasterizacao) {
            PanelMenuRasterizacao rast = (PanelMenuRasterizacao) instance;
            if (rast.getTipoAlgoritimo().equals(RasterizacaoEnum.DDA)) {
                Rasterizacao.dda(rast.getPontoInicial(), rast.getPontoFinal(), rast.getColor(), panelPlanoCartesiano, rast.getTextAreaResult());
            } else if (rast.getTipoAlgoritimo().equals(RasterizacaoEnum.PONTO_MEDIO)) {
                Rasterizacao.pontoMedio(rast.getPontoInicial(), rast.getPontoFinal(), rast.getColor(), panelPlanoCartesiano, rast.getTextAreaResult());
            }
        } else if (instance instanceof PanelMenuCircunferencia) {
            // objeto circ possui o getRaio, getColor, getTextAreaResult e getTipoAlgoritimo
            PanelMenuCircunferencia circ = (PanelMenuCircunferencia) instance;

            switch (circ.getTipoAlgoritimo()) {
                case PONTO_MEDIO:
                    Circunferencia.funcaoPontoMedio((int) circ.getRaioX(), circ.getColor(), panelPlanoCartesiano);
                    break;
                case EQUACAO_EXPLICITA:
                    Circunferencia.funcaoExplicita((int) circ.getRaioX(), circ.getColor(), panelPlanoCartesiano);
                    break;
                case TRIGONOMETRIA:
                    Circunferencia.funcaoTrigonometria((int) circ.getRaioX(), circ.getColor(), panelPlanoCartesiano);
                    break;
                case ELIPSE:
                    Circunferencia.funcaoElipse((int) circ.getRaioX(), (int) circ.getRaioY(), circ.getColor(), panelPlanoCartesiano);
                default:
                    break;
            }
        } else if (instance instanceof PanelMenu2D) {
            PanelMenu2D menu2D = (PanelMenu2D) instance;
            if (listaGLOBAL != null) {
                switch (menu2D.getTipoAlgoritimo()) {
                    case TRANSLACAO: {
                        List<Ponto> listaPontos = DialogDesenhaObjetos.getLista();
                        Transformacoes2D.translacao(listaPontos, menu2D.getValorX(), menu2D.getValorY(), PanelPlanoCartesiano.getInstance(), menu2D.getColor());
                        break;
                    }
                    case ESCALA: {
                        List<Ponto> listaPontos = DialogDesenhaObjetos.getLista();
                        Transformacoes2D.escala(listaPontos, menu2D.getValorX(), menu2D.getValorY(), PanelPlanoCartesiano.getInstance(), menu2D.getColor());
                        break;
                    }
                    case ROTACAO: {
                        List<Ponto> listaPontos = DialogDesenhaObjetos.getLista();
                        Transformacoes2D.rotacao(listaPontos, (int) menu2D.getAngulo(), PanelPlanoCartesiano.getInstance(), menu2D.getColor());
                        break;
                    }
                    case REFLEXAO: {
                        List<Ponto> listaPontos = DialogDesenhaObjetos.getLista();
                        Transformacoes2D.reflexao(listaPontos, menu2D.getEixo(), PanelPlanoCartesiano.getInstance(), menu2D.getColor());
                        break;
                    }
                    case CISALHAMENTO: {
                        List<Ponto> listaPontos = DialogDesenhaObjetos.getLista();
                        Transformacoes2D.cisalhamento(listaPontos, menu2D.getValorX(), menu2D.getValorY(), PanelPlanoCartesiano.getInstance(), menu2D.getColor());
                        break;
                    }
                    default:
                        break;
                }
            }
        }
    }

    /**
     * Calcula e exibe o sistema de coordenadas de acordo com os pontos no plano
     * cartesiano O Evento mouseMoved é utilizado para pegar as coordenadas no
     * plano cartesiano
     */
    private void sistemaCoordenadas() {
        panelPlanoCartesiano.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseMoved(MouseEvent e) {
                super.mouseMoved(e); //To change body of generated methods, choose Tools | Templates.

                // Pega a instancia do Plano Cartesiano
                PanelPlanoCartesiano planoCartesiano = PanelPlanoCartesiano.getInstance();

                // Calcula o dc - Entrada de dispositivo | Será o mesmo que a saída
                int dcx = e.getX() - planoCartesiano.getValorCentroX();
                int dcy = (e.getY() - planoCartesiano.getValorCentroY()) * -1;

                // Calcula o ndc - Normalização do dispositivo
                float ndcx = FuncoesDeNormalizacao.calcularNDCX(planoCartesiano.getLargura(), dcx);
                float ndcy = FuncoesDeNormalizacao.calcularNDCX(planoCartesiano.getAltura(), dcy);

                labelNDCX.setText(String.format("%.6f", ndcx));
                labelNDCY.setText(String.format("%.6f", ndcy));

                labelDCX.setText(String.valueOf(FuncoesDeNormalizacao.calcularDCX(planoCartesiano.getLargura(), ndcx)));
                labelDCY.setText(String.valueOf(FuncoesDeNormalizacao.calcularDCY(planoCartesiano.getAltura(), ndcy)));

                labelX.setText(String.valueOf(Math.round(dcx)));
                labelY.setText(String.valueOf(Math.round(dcy)));
            }
        });
    }
}
