package br.edu.uepb.cg.dialog;

import br.edu.uepb.cg.panels.PanelMenu2D;
import br.edu.uepb.cg.panels.PanelPlanoCartesiano;
import br.edu.uepb.cg.retas.Ponto;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;

/**
 * JDialog que exibe informações sobre o projeto
 *
 * @author Douglas Rafael
 */
public class DialogDesenhaObjetos extends javax.swing.JDialog {

    public static List<Ponto> listaGLOBAL;

    /**
     * Construtor do JDialog
     *
     * @param parent
     * @param modal
     */
    public DialogDesenhaObjetos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        spinnerZ.setVisible(false);
        lbZ.setVisible(false);
    }

    public static List<Ponto> getLista() {
        return listaGLOBAL;
    }

    public static void setLista(List<Ponto> lista) {
        DialogDesenhaObjetos.listaGLOBAL = lista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        valorX = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        valorY = new javax.swing.JSpinner();
        buttonGroupTipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radioRect = new javax.swing.JRadioButton();
        radioCubo = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        lbX = new javax.swing.JLabel();
        spinnerX = new javax.swing.JSpinner();
        spinnerY = new javax.swing.JSpinner();
        spinnerZ = new javax.swing.JSpinner();
        lbY = new javax.swing.JLabel();
        lbZ = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Valores"));

        valorX.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        valorX.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 0.1f));
        valorX.setMaximumSize(new java.awt.Dimension(30, 25));
        valorX.setMinimumSize(new java.awt.Dimension(30, 25));
        valorX.setPreferredSize(new java.awt.Dimension(30, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("X");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Y");

        valorY.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        valorY.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 0.1f));
        valorY.setMaximumSize(new java.awt.Dimension(30, 25));
        valorY.setMinimumSize(new java.awt.Dimension(30, 25));
        valorY.setPreferredSize(new java.awt.Dimension(30, 25));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4)
                        .addGap(32, 32, 32))
                    .addComponent(valorX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(valorY, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel5)))
                .addGap(43, 43, 43))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Desenhar Objeto");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../assets/images/icon.png")));
        setMinimumSize(new java.awt.Dimension(400, 240));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo"));

        buttonGroupTipo.add(radioRect);
        radioRect.setSelected(true);
        radioRect.setText("Retângulo");
        radioRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTipo(evt);
            }
        });

        buttonGroupTipo.add(radioCubo);
        radioCubo.setText("Cubo");
        radioCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTipo(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioCubo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioRect)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioRect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioCubo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Valores"));

        lbX.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbX.setText("X");

        spinnerX.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        spinnerX.setModel(new javax.swing.SpinnerNumberModel(100, null, null, 1));
        spinnerX.setMaximumSize(new java.awt.Dimension(30, 25));
        spinnerX.setMinimumSize(new java.awt.Dimension(30, 25));
        spinnerX.setPreferredSize(new java.awt.Dimension(30, 25));

        spinnerY.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        spinnerY.setModel(new javax.swing.SpinnerNumberModel(100, null, null, 1));
        spinnerY.setMaximumSize(new java.awt.Dimension(30, 25));
        spinnerY.setMinimumSize(new java.awt.Dimension(30, 25));
        spinnerY.setPreferredSize(new java.awt.Dimension(30, 25));

        spinnerZ.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        spinnerZ.setModel(new javax.swing.SpinnerNumberModel(100, null, null, 1));
        spinnerZ.setMaximumSize(new java.awt.Dimension(30, 25));
        spinnerZ.setMinimumSize(new java.awt.Dimension(30, 25));
        spinnerZ.setPreferredSize(new java.awt.Dimension(30, 25));

        lbY.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbY.setText("Y");

        lbZ.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbZ.setText("Z");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinnerX, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lbX)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(spinnerY, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lbY)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinnerZ, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(lbZ)
                        .addGap(34, 34, 34)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbX)
                    .addComponent(lbY)
                    .addComponent(lbZ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Desenhar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desenharObjeto(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void desenharObjeto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desenharObjeto
        listaGLOBAL = new ArrayList<>();

        if (radioRect.isSelected()) {
            int width = (int) spinnerX.getValue();
            int height = (int) spinnerY.getValue();

            listaGLOBAL.add(new Ponto(0, 0)); // A
            listaGLOBAL.add(new Ponto(width, 0)); // B
            listaGLOBAL.add(new Ponto(width, height)); // C
            listaGLOBAL.add(new Ponto(0, height)); // D

            /**
             * Pega a instancia do plano cartesiano para limpa-lo
             */
            PanelPlanoCartesiano panelPlanoCartesiano = PanelPlanoCartesiano.getInstance();
            panelPlanoCartesiano.redesenha();

            // pega instancia do PanelMenu2D para acessar a cor selecionada
            PanelMenu2D menu2D = PanelMenu2D.getInstance();
                
            // Pega a instancia do graphics para desenhar no plano cartesiano    
            Graphics g2D = (Graphics) panelPlanoCartesiano.getGraphics();
            g2D.setColor(menu2D.getColor());

            // Desenha o retangulo
            g2D.drawRect(panelPlanoCartesiano.getValorCentroX(), panelPlanoCartesiano.getValorCentroY() - height, width, height);

//            menu2D.setRect(rect);
//            menu2D.setPonto(new Ponto(panelPlanoCartesiano.getValorCentroX(), panelPlanoCartesiano.getValorCentroY() - height));
        } else if (radioCubo.isSelected()) {

//            int x = (int) spinnerX.getValue();
//            int y = (int) spinnerY.getValue();
//            int z = (int) spinnerZ.getValue();
//
//            PanelPlanoCartesiano panelPlanoCartesiano = PanelPlanoCartesiano.getInstance();
//            panelPlanoCartesiano.redesenha();
//            Graphics g = panelPlanoCartesiano.getGraphics();
//            g.setColor(Color.BLUE); //  cor default do objeto
//            
//            
//
//            g.drawLine(panelPlanoCartesiano.getValorCentroX() + (-z / 2), panelPlanoCartesiano.getValorCentroY() - (-z / 2), panelPlanoCartesiano.getValorCentroX() + y, panelPlanoCartesiano.getValorCentroY() - (-z / 2));//A-B
//            g.drawLine(panelPlanoCartesiano.getValorCentroX() + y, panelPlanoCartesiano.getValorCentroY() - (-z / 2), panelPlanoCartesiano.getValorCentroX() + y, panelPlanoCartesiano.getValorCentroY() - z);//B-C
//            g.drawLine(panelPlanoCartesiano.getValorCentroX() + y, panelPlanoCartesiano.getValorCentroY() - z, panelPlanoCartesiano.getValorCentroX() + (-z / 2), panelPlanoCartesiano.getValorCentroY() - z);//C-D
//            g.drawLine(panelPlanoCartesiano.getValorCentroX() + (-z / 2), panelPlanoCartesiano.getValorCentroY() - z, panelPlanoCartesiano.getValorCentroX() + (-z / 2), panelPlanoCartesiano.getValorCentroY() - (-z / 2));//D-A
//
//            g.drawLine(panelPlanoCartesiano.getValorCentroX() + 0, panelPlanoCartesiano.getValorCentroY() - 0, panelPlanoCartesiano.getValorCentroX() + x, panelPlanoCartesiano.getValorCentroY() - 0);//E-F
//            g.drawLine(panelPlanoCartesiano.getValorCentroX() + x, panelPlanoCartesiano.getValorCentroY() - 0, panelPlanoCartesiano.getValorCentroX() + x, panelPlanoCartesiano.getValorCentroY() - y);//F-H
//            g.drawLine(panelPlanoCartesiano.getValorCentroX() + x, panelPlanoCartesiano.getValorCentroY() - y, panelPlanoCartesiano.getValorCentroX() + 0, panelPlanoCartesiano.getValorCentroY() - y);//H-G
//            g.drawLine(panelPlanoCartesiano.getValorCentroX() + 0, panelPlanoCartesiano.getValorCentroY() - y, panelPlanoCartesiano.getValorCentroX() + 0, panelPlanoCartesiano.getValorCentroY() - 0);//H-A
//
//            g.drawLine(panelPlanoCartesiano.getValorCentroX() + (-z / 2), panelPlanoCartesiano.getValorCentroY() - (-z / 2), panelPlanoCartesiano.getValorCentroX() + 0, panelPlanoCartesiano.getValorCentroY() - 0);//A-E
//            g.drawLine(panelPlanoCartesiano.getValorCentroX() + y, panelPlanoCartesiano.getValorCentroY() + (-z / 2), panelPlanoCartesiano.getValorCentroX() + x, panelPlanoCartesiano.getValorCentroY() - 0);//B-F
//            g.drawLine(panelPlanoCartesiano.getValorCentroX() + (-z / 2), panelPlanoCartesiano.getValorCentroY() - z, panelPlanoCartesiano.getValorCentroX() + 0, panelPlanoCartesiano.getValorCentroY() - y);//D-G
//            g.drawLine(panelPlanoCartesiano.getValorCentroX() + y, panelPlanoCartesiano.getValorCentroY() - z, panelPlanoCartesiano.getValorCentroX() + x, panelPlanoCartesiano.getValorCentroY() - y);//C-H
        }

        this.dispose(); // fecha a janela
    }//GEN-LAST:event_desenharObjeto

    private void selectTipo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTipo
        if (radioCubo.isSelected()) {
            spinnerZ.setVisible(true);
            lbZ.setVisible(true);
        } else {
            spinnerZ.setVisible(false);
            lbZ.setVisible(false);
        }
    }//GEN-LAST:event_selectTipo

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogDesenhaObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogDesenhaObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogDesenhaObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogDesenhaObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogDesenhaObjetos dialog = new DialogDesenhaObjetos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbX;
    private javax.swing.JLabel lbY;
    private javax.swing.JLabel lbZ;
    private javax.swing.JRadioButton radioCubo;
    private javax.swing.JRadioButton radioRect;
    private javax.swing.JSpinner spinnerX;
    private javax.swing.JSpinner spinnerY;
    private javax.swing.JSpinner spinnerZ;
    private javax.swing.JSpinner valorX;
    private javax.swing.JSpinner valorY;
    // End of variables declaration//GEN-END:variables
}
